FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y ubuntu-server
RUN apt-get -y install nodejs
RUN apt-get -y install npm
RUN apt-get -y install openjdk-8-jdk

